### ISSUE TITLE
Disappears the upper right menu bar 

### ISSUE THREAD

**Issue by torsday** [josephhitchcock/roam-themes#1]
<img width="361" alt="Screen Shot 2020-06-16 at 06 46 59" src="https://user-images.githubusercontent.com/281985/84782893-7839c680-af9d-11ea-82f0-c3d7cc089ba4.png">

^ this is what's missing

**Comment by josephhitchcock** [comment]
All of that functionality is still available, it's just been relocated to the left side of the main panel.

![image](https://user-images.githubusercontent.com/10837901/84852214-1e72e400-b011-11ea-9142-9d7e1dfe9be0.png)
